.TH "bus_stats.payload_size" 3 "Sat Oct 18 2025" "CANopen-Sniffer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_stats.payload_size \- Tracks cumulative payload sizes for key CANopen message types\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Tracks cumulative payload sizes for key CANopen message types\&. 

Used to compute data throughput for PDO and SDO messages\&. 
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefault_factory\fP"
.br
.ti -1c
.RI "\fBdict\fP"
.br
.RI "Dictionary holding total payload size per frame type\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "default_factory\fC [static]\fP"

.SS "dict\fC [static]\fP"

.PP
Dictionary holding total payload size per frame type\&. Initialized for PDO and SDO response messages\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Sniffer from the source code\&.
