.TH "bus_stats.error_stats" 3 "Wed Nov 12 2025" "CANopen-Sniffer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_stats.error_stats \- Tracks error-related information observed on the CANopen bus\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Tracks error-related information observed on the CANopen bus\&. 

Maintains time and frame references for the most recent errors seen per node\&. 
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefault_factory\fP"
.br
.ti -1c
.RI "\fBdict\fP"
.br
.RI "Dictionary mapping node IDs to timestamps of last error\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "default_factory\fC [static]\fP"

.SS "dict\fC [static]\fP"

.PP
Dictionary mapping node IDs to timestamps of last error\&. Dictionary mapping node IDs to the last error frame received\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Sniffer from the source code\&.
