.TH "canopen_sniffer.py" 3 "Sun Dec 14 2025" "CANopen-Sniffer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
canopen_sniffer.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcan_sniffer\fP"
.br
.RI "CAN bus sniffer thread\&. "
.ti -1c
.RI "class \fBeds_parser\fP"
.br
.RI "Parser for CANopen EDS (Electronic Data Sheet) files\&. "
.ti -1c
.RI "class \fBprocess_frame\fP"
.br
.RI "Processor thread that consumes CAN frames and updates statistics\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcanopen_sniffer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.RI "Main entry point for the CANopen bus sniffer application\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Sniffer from the source code\&.
