.TH "DisplayCLI" 3 "Wed Nov 12 2025" "CANopen-Sniffer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayCLI
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Rich-based CLI display thread that consumes processed_frame queue and renders
Protocol, PDO, SDO tables plus Bus Stats in a live layout.

NOTE: This DisplayCLI reads all rate/utility information from bus_stats snapshot
(snapshot.rates.latest and snapshot.rates.history). It does not perform any local
rate calculation or use bitrate directly.

.fi
.PP
 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBbus_stats\fP \fBstats\fP, queue\&.Queue \fBprocessed_frame\fP, bool \fBfixed\fP=False)"
.br
.ti -1c
.RI "def \fBbuild_bus_stats_table\fP (self)"
.br
.ti -1c
.RI "def \fBrender_tables\fP (self)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBsparkline\fP (self, history, style='white')"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconsole\fP"
.br
.ti -1c
.RI "\fBDATA_TABLE_HEIGHT\fP"
.br
.ti -1c
.RI "\fBfixed\fP"
.br
.ti -1c
.RI "\fBfixed_pdo\fP"
.br
.ti -1c
.RI "\fBfixed_proto\fP"
.br
.ti -1c
.RI "\fBfixed_sdo\fP"
.br
.ti -1c
.RI "\fBGRAPH_WIDTH\fP"
.br
.ti -1c
.RI "\fBlog\fP"
.br
.ti -1c
.RI "\fBpdo_frames\fP"
.br
.ti -1c
.RI "\fBprocessed_frame\fP"
.br
.ti -1c
.RI "\fBproto_frames\fP"
.br
.ti -1c
.RI "\fBPROTOCOL_TABLE_HEIGHT\fP"
.br
.ti -1c
.RI "\fBsdo_frames\fP"
.br
.ti -1c
.RI "\fBstats\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self, \fBbus_stats\fP stats, queue\&.Queue processed_frame, bool  fixed = \fCFalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS "def build_bus_stats_table ( self)"

.PP
.nf
Build a Bus Stats table by querying latest stats snapshot (bus_stats owns all calculations).
.fi
.PP
 
.SS "def render_tables ( self)"

.SS "def run ( self)"

.SS "def sparkline ( self,  history,  style = \fC'white'\fP)"

.PP
.nf
Create a compact sparkline Text from a numeric history sequence.
.fi
.PP
 
.SS "def stop ( self)"

.SH "Member Data Documentation"
.PP 
.SS "console"

.SS "DATA_TABLE_HEIGHT"

.SS "fixed"

.SS "fixed_pdo"

.SS "fixed_proto"

.SS "fixed_sdo"

.SS "GRAPH_WIDTH"

.SS "log"

.SS "pdo_frames"

.SS "processed_frame"

.SS "proto_frames"

.SS "PROTOCOL_TABLE_HEIGHT"

.SS "sdo_frames"

.SS "stats"


.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Sniffer from the source code\&.
