.TH "DisplayGUI" 3 "Sat Nov 15 2025" "CANopen-Sniffer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Placeholder GUI display thread — for now consume queue and log the frames.
   Replace this run() with actual Qt event integration later if needed.

.fi
.PP
 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, queue\&.Queue \fBprocessed_frame\fP)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog\fP"
.br
.ti -1c
.RI "\fBprocessed_frame\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self, queue\&.Queue processed_frame)"

.SH "Member Function Documentation"
.PP 
.SS "def run ( self)"

.SS "def stop ( self)"

.SH "Member Data Documentation"
.PP 
.SS "log"

.SS "processed_frame"


.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Sniffer from the source code\&.
