.TH "display_gui.py" 3 "Sun Dec 14 2025" "CANopen-Sniffer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_gui.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplay_gui\fP"
.br
.RI "Placeholder GUI display thread — for now consume queue and log the frames\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdisplay_gui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Sniffer from the source code\&.
