.TH "frame_type" 3 "Mon Dec 22 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frame_type \- Types of CANopen messages\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SH "Detailed Description"
.PP 
Types of CANopen messages\&. 

This enumeration defines the various message types that can appear on a CANopen network\&. 
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBEMCY\fP = 1"
.br
.RI "Emergency message\&. "
.ti -1c
.RI "int \fBHB\fP = 2"
.br
.RI "Heartbeat message\&. "
.ti -1c
.RI "int \fBNMT\fP = 3"
.br
.RI "Network Management message\&. "
.ti -1c
.RI "int \fBPDO\fP = 4"
.br
.RI "Process Data Object message\&. "
.ti -1c
.RI "int \fBSDO_REQ\fP = 5"
.br
.RI "Service Data Object request message\&. "
.ti -1c
.RI "int \fBSDO_RES\fP = 6"
.br
.RI "Service Data Object response message\&. "
.ti -1c
.RI "int \fBSYNC\fP = 7"
.br
.RI "CANopen synchronization message\&. "
.ti -1c
.RI "int \fBTIME\fP = 8"
.br
.RI "Timestamp message\&. "
.ti -1c
.RI "int \fBUNKNOWN\fP = 9"
.br
.RI "Other or unknown message type\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int EMCY = 1\fC [static]\fP"

.PP
Emergency message\&. 
.SS "int HB = 2\fC [static]\fP"

.PP
Heartbeat message\&. 
.SS "int NMT = 3\fC [static]\fP"

.PP
Network Management message\&. 
.SS "int PDO = 4\fC [static]\fP"

.PP
Process Data Object message\&. 
.SS "int SDO_REQ = 5\fC [static]\fP"

.PP
Service Data Object request message\&. 
.SS "int SDO_RES = 6\fC [static]\fP"

.PP
Service Data Object response message\&. 
.SS "int SYNC = 7\fC [static]\fP"

.PP
CANopen synchronization message\&. 
.SS "int TIME = 8\fC [static]\fP"

.PP
Timestamp message\&. 
.SS "int UNKNOWN = 9\fC [static]\fP"

.PP
Other or unknown message type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
