.TH "bus_stats.rates_stats" 3 "Wed Dec 17 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_stats.rates_stats \- Records frame rate statistics (PDO, SDO, total, etc\&.)  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Records frame rate statistics (PDO, SDO, total, etc\&.) 

Tracks last update time and last frame counts for rate computations\&. 
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBdefault_factory\fP"
.br
.ti -1c
.RI "\fBdict\fP"
.br
.ti -1c
.RI "\fBfloat\fP"
.br
.ti -1c
.RI "\fBlist\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "default_factory\fC [static]\fP"

.SS "dict\fC [static]\fP"

.SS "float\fC [static]\fP"

.SS "list\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
