.TH "bus_stats.stats_data" 3 "Mon Dec 29 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_stats.stats_data \- Consolidated data record for overall bus statistics\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Consolidated data record for overall bus statistics\&. 

This dataclass aggregates multiple categories of bus-level statistics, including nodes, top talkers, and various measurement substructures\&. 
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBCounter\fP"
.br
.RI "Counter tracking nodes sending the most messages\&. "
.ti -1c
.RI "\fBdefault_factory\fP"
.br
.RI "Reference to \fBbus_stats\&.frame_count\fP data structure\&. "
.ti -1c
.RI "\fBdict\fP"
.br
.RI "Last-seen timestamp per node (used for inactivity detection)\&. "
.ti -1c
.RI "\fBfloat\fP"
.br
.RI "Timestamp marking when statistics collection started\&. "
.ti -1c
.RI "\fBset\fP"
.br
.RI "Set of node IDs currently active on the CANopen network\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Counter\fC [static]\fP"

.PP
Counter tracking nodes sending the most messages\&. 
.SS "default_factory\fC [static]\fP"

.PP
Reference to \fBbus_stats\&.frame_count\fP data structure\&. Reference to \fBbus_stats\&.error_stats\fP data structure\&.
.PP
Reference to \fBbus_stats\&.sdo_stats\fP data structure\&.
.PP
Reference to \fBbus_stats\&.payload_size\fP data structure\&. 
.SS "dict\fC [static]\fP"

.PP
Last-seen timestamp per node (used for inactivity detection)\&. 
.SS "float\fC [static]\fP"

.PP
Timestamp marking when statistics collection started\&. 
.SS "set\fC [static]\fP"

.PP
Set of node IDs currently active on the CANopen network\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
