.TH "bus_stats.py" 3 "Mon Dec 29 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_stats.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbus_stats\fP"
.br
.RI "Container class for all CANopen bus statistics\&. "
.ti -1c
.RI "class \fBbus_stats\&.error_stats\fP"
.br
.RI "Tracks error-related information observed on the CANopen bus\&. "
.ti -1c
.RI "class \fBbus_stats\&.frame_count\fP"
.br
.RI "Tracks the number of frames by CANopen message type\&. "
.ti -1c
.RI "class \fBbus_stats\&.payload_size\fP"
.br
.RI "Tracks cumulative payload sizes for key CANopen message types\&. "
.ti -1c
.RI "class \fBbus_stats\&.rates_stats\fP"
.br
.RI "Records frame rate statistics (PDO, SDO, total, etc\&.) "
.ti -1c
.RI "class \fBbus_stats\&.sdo_stats\fP"
.br
.RI "Records SDO (Service Data Object) communication statistics\&. "
.ti -1c
.RI "class \fBbus_stats\&.stats_data\fP"
.br
.RI "Consolidated data record for overall bus statistics\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbus_stats\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
