.TH "display_tui" 3 "Fri Jan 2 2026" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_tui
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplay_tui\fP"
.br
.RI "Textual-based TUI implementation for CANopen protocol\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBApp\fP = None"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "App = None"

.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
