.TH "display_cli" 3 "Sun Dec 14 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_cli
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplay_cli\fP"
.br
.RI "Rich-based CLI display thread that consumes processed_frame queue and renders Protocol, PDO, SDO tables plus Bus Stats in a live layout\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
