.TH "display_gui" 3 "Sun Dec 14 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_gui \- Placeholder GUI display thread — for now consume queue and log the frames\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SH "Detailed Description"
.PP 
Placeholder GUI display thread — for now consume queue and log the frames\&. 

Replace this \fBrun()\fP with actual Qt event integration later if needed\&. 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, queue\&.Queue \fBprocessed_frame\fP)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog\fP"
.br
.ti -1c
.RI "\fBprocessed_frame\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self, queue\&.Queue processed_frame)"

.SH "Member Function Documentation"
.PP 
.SS "def run ( self)"

.SS "def stop ( self)"

.SH "Member Data Documentation"
.PP 
.SS "log"

.SS "processed_frame"


.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
