.TH "display_cli.py" 3 "Tue Jan 6 2026" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_cli.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplay_cli\fP"
.br
.RI "Rich-based CLI display thread that consumes processed_frame queue and renders Protocol, PDO, SDO tables plus Bus Stats in a live layout\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdisplay_cli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
