.TH "display_tui.py" 3 "Mon Dec 22 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display_tui.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplay_tui\fP"
.br
.RI "Textual-based TUI implementation for CANopen protocol\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdisplay_tui\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBApp\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
