.TH "eds_parser" 3 "Wed Dec 17 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eds_parser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeds_parser\fP"
.br
.RI "Parser for CANopen EDS (Electronic Data Sheet) files\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
