.TH "process_frames" 3 "Thu Dec 18 2025" "CANopen-Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
process_frames
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBprocess_frames\fP"
.br
.RI "Processor thread that consumes CAN frames and updates statistics\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CANopen-Analyzer from the source code\&.
