classDiagram
class BusStats {
    +frame_count
    +payload_size
    +sdo_stats
    +error_stats
    +set_start_time()
    +increment_frame(ftype)
}

class eds_parser {
    -eds_path
    -name_map
    -pdo_map
    +build_name_map()
    +parse_pdo_map()
}

class can_sniffer {
    -interface
    -raw_frame
    -bus
    -network
    -export
    +start()
    +stop()
    +handle_message(msg)
}

class process_frame {
    -raw_frame
    -eds_map
    -stats
    -export
    +run()
    +stop()
    +save_frame_to_csv(...)
}

class main {
    +main()
}

BusStats "1" <-- "1" process_frame : updates >
eds_parser "1" <-- "1" process_frame : uses >
can_sniffer "1" -- "1" process_frame : shares raw_frame with >
main "1" o-- "1" can_sniffer : creates >
main "1" o-- "1" process_frame : creates >
main "1" o-- "1" eds_parser : creates >
